# Generated by Django 3.0.5 on 2020-04-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_profile', '0003_auto_20200427_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPointName', models.CharField(max_length=250)),
                ('salutationCode', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('houseNumber', models.CharField(max_length=20)),
                ('houseNumberExtended', models.CharField(max_length=20)),
                ('addressSupplement', models.CharField(max_length=50)),
                ('extraAddressInformation', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('countryCode', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('vatNumber', models.CharField(max_length=100)),
                ('chamberOfCommerceNumber', models.CharField(max_length=100)),
                ('orderReference', models.CharField(max_length=100)),
                ('deliveryPhoneNumber', models.CharField(blank=True, max_length=13, null=True, verbose_name='Contact no')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpPointName', models.CharField(max_length=250)),
                ('salutationCode', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('houseNumber', models.CharField(max_length=20)),
                ('houseNumberExtended', models.CharField(max_length=20)),
                ('addressSupplement', models.CharField(max_length=50)),
                ('extraAddressInformation', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('countryCode', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('vatNumber', models.CharField(max_length=100)),
                ('chamberOfCommerceNumber', models.CharField(max_length=100)),
                ('orderReference', models.CharField(max_length=100)),
                ('deliveryPhoneNumber', models.CharField(blank=True, max_length=13, null=True, verbose_name='Contact no')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=150)),
                ('orderItemId', models.CharField(max_length=150)),
                ('orderDate', models.CharField(max_length=200)),
                ('latestDeliveryDate', models.CharField(max_length=200)),
                ('ean', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('offerPrice', models.FloatField(default=0.0)),
                ('offerCondition', models.CharField(max_length=200)),
                ('offerReference', models.CharField(max_length=20)),
                ('fulfilmentMethod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportId', models.IntegerField(default=0)),
                ('transporterCode', models.CharField(max_length=10)),
                ('trackAndTrace', models.CharField(max_length=50)),
                ('shippingLabelId', models.IntegerField(default=0)),
                ('shippingLabelCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.IntegerField()),
                ('shipmentDate', models.CharField(max_length=150)),
                ('shipmentReference', models.CharField(max_length=100)),
                ('pickUpPoint', models.BooleanField(default=False)),
                ('billingDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.BillingDetails')),
                ('customerDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.CustomerDetails')),
                ('orderDetails', models.ManyToManyField(to='shipments.OrderDetails')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_profile.SellerProfile')),
                ('transportDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.TransportDetails')),
            ],
        ),
    ]
