# Generated by Django 3.0.5 on 2020-04-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='addressSupplement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='chamberOfCommerceNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='extraAddressInformation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='firstName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='houseNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='houseNumberExtended',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='orderReference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='pickUpPointName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='streetName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='surname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='vatNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='addressSupplement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='chamberOfCommerceNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='extraAddressInformation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='firstName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='houseNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='houseNumberExtended',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='orderReference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='pickUpPointName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='streetName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='surname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='vatNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='billingDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.BillingDetails'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='customerDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.CustomerDetails'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='orderDetails',
            field=models.ManyToManyField(blank=True, to='shipments.OrderDetails'),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='transportDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipments.TransportDetails'),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='shippingLabelCode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
