# Generated by Django 3.0.5 on 2020-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20200427_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='shipmentId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
