# Generated by Django 3.0.5 on 2020-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerprofile',
            unique_together=set(),
        ),
    ]
