# Generated by Django 3.0.5 on 2020-04-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0002_auto_20200427_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerprofile',
            unique_together={('seller_name', 'client_id', 'client_secret')},
        ),
    ]
